version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    ports:
      - 3307:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ficticiys_clean:/var/lib/mysql
    networks:
      - ficticiys_clean_net
  ficticius-clean-prod:
    build: ./
    container_name: ficticius-clean-prod
    image: ficticius-clean-prod
    environment:
      spring.profiles.active: prod
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ficticius
      DB_USERNAME: root
      DB_PASSWORD: 123456
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - ficticiys_clean_net
volumes:
  ficticiys_clean:
networks:
  ficticiys_clean_net:
